version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/development/web/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - web_bundle:/usr/local/bundle
    depends_on:
      - psql
    entrypoint:
      - bash
      - -c
      - rm -f /app/tmp/pids/server.pid && yarn install --check-files && bundle install && rails s -b 0.0.0.0
  psql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    # volumes:
    #   - psql_data:/var/lib/postgresql/data
volumes:
  psql_data:
  web_bundle:

