version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/web/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - web_bundle:/usr/local/bundle
    depends_on:
      - psql
    command: ./docker/production/web/command.sh
  psql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pingpong_production
    volumes:
      - psql_data:/var/lib/postgresql/data
volumes:
  psql_data:
  web_bundle:

